CREATE TABLE IF NOT EXISTS prod_star_date_dimension (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, date DATE, day INTEGER, day_of_week TEXT, month INTEGER, month_name TEXT, year INTEGER);

CREATE TABLE IF NOT EXISTS prod_star_game_update_events_dimension (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, date DATE, platform TEXT, event_name TEXT);

CREATE TABLE IF NOT EXISTS prod_star_crime_media_coverage_dimension (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, date DATE, transcripts_with_mentions_of_crime INTEGER, total_transcripts INTEGER, crime_mention_rate NUMERIC);

CREATE TABLE IF NOT EXISTS prod_star_crime_reports_la_dimension (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, record_number BIGINT, date DATE, crime_code INTEGER, crime_committed_description TEXT, type_of_structure_vehicle_location_code INTEGER, type_of_structure_vehicle_location_description TEXT, type_of_weapon_code INTEGER, type_of_weapon_description TEXT, status_of_the_crime_code TEXT, status_of_the_crime_description TEXT, latitude NUMERIC, longitude NUMERIC);

CREATE TABLE IF NOT EXISTS prod_star_fact_table (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, date_dimension INTEGER REFERENCES prod_star_date_dimension(id), game_update_events_dimension INTEGER REFERENCES prod_star_game_update_events_dimension(id),  crime_media_coverage_dimension INTEGER REFERENCES prod_star_crime_media_coverage_dimension(id), crime_reports_la_dimension INTEGER REFERENCES prod_star_crime_reports_la_dimension(id), date DATE, 
gta_5_players INTEGER, gta_5_viewers INTEGER, gta_5_update_on_this_day BOOLEAN, news_mention_crime_rate NUMERIC, amount_of_crime_reports_la INTEGER);
